project: 'direct_bind'
resume_id: null
name: test_run

val_check_interval: 20000

dataset: bigbind_act
data:
  cache: true

  use_rec: true
  use_lig: true
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      knn_rad: 20
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

losses:
  act_mse_lambda: 1.0

metrics:
  - act_r2

batch_size: 16
optimizer: adamw
learn_rate: 1e-4
max_epochs: 1000

model:

  type: gnn_bind

  use_rec: true
  use_lig: true
  
  rec_encoder:
    node_embed_size: 16
    edge_embed_size: 16
    num_mpnn_layers: 1
    edge_hidden_size: 8
    node_hidden_sizes: [ 16, 16, 16, 16, 16 ]

  lig_encoder:
    node_embed_size: 8
    edge_embed_size: 16
    num_mpnn_layers: 2
    edge_hidden_size: 16
    node_hidden_sizes: [ 16, 16, 16, 16, 16 ]
    
  out_mlp_sizes: [64]
