project: 'direct_bind'
resume_id: null
name: test_run

val_check_interval: 10000
max_val_size: 10000

dataset: bigbind_act
data:
  cache: true
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "type" ]
    residue_feats: [ "type" ]
    edge_method:
      type: "knn"
      knn_rad: 20
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False


batch_size: 2
optimizer: adamw
learn_rate: 1e-4
max_epochs: 1000

model:

  type: gnn_bind

  use_rec: true
  use_lig: true
  
  rec_encoder:
    embed_size: 32
    num_mpnn_layers: 1
    edge_hidden_size: 8
    node_hidden_sizes: [128, 128, 128, 128, 128]

  lig_encoder:
    num_mpnn_layers: 2
    edge_hidden_size: 32
    node_hidden_sizes: [128, 128, 128, 128, 128]
    
  out_mlp_sizes: [64]
