project: null
resume_id: null
name: test_run

val_check_interval: 10000

dataset: bigbind_fp
data:
  cache: true
  fp_type: "morgan"
  morgan_radius: 2
  morgan_bits: 2048
  
losses:
  act_mse_lambda: 1.0

metrics:
  - act_r2

batch_size: 16
optimizer: adamw
learn_rate: 1e-3
max_epochs: 1000

model:

  type: fp_nn

  hidden_sizes: [ 2048, 1024, 512, 256 ]
