project: 'direct_bind'
resume_id: null
name: test_run

val_check_interval: 5000

dataset: bigbind_act
data:
  cache: true

  use_rec: true
  use_lig: true

  only_ki_kd: false
  
  lig_graph:
    atom_feats: [ "element", "formal_charge", "hybridization", "is_aromatic", "numH"]
    bond_feats:
      bond_order: true

  rec_graph:
    only_pocket: true
    node_type: "residue"
    atom_feats: [ "atom_type" ]
    residue_feats: [ "residue_type" ]
    edge_method:
      type: "knn"
      knn_rad: 20
      max_neighbors: null
    edge_feats: [ "dist"]
    include_h: False

losses:
  act_mse_lambda: 1.0

metrics:
  - act_r2

batch_size: 32
optimizer: adamw
learn_rate: 1e-4
max_epochs: 1000

model:

  type: outer_prod_gnn
  
  rec_encoder:
    node_embed_size: 32
    edge_embed_size: 32
    num_mpnn_layers: 8
    edge_hidden_size: 8
    out_size: 32

  lig_encoder:
    node_embed_size: 8
    edge_embed_size: 32
    num_mpnn_layers: 8
    edge_hidden_size: 32
    out_size: 32

  out_mlp_sizes: [64]
